name: jobs examples
on:
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step do job build
        run: echo Hello, world! Build.
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step do deploy
        run: echo Hello, world! Deploy.
