name: jobs examples
on:
  push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: example of invalid command
        run: echo Hello, world! Build failed.
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step do deploy
        run: echo Hello, world! Deploy.
